version: "3.7"

services:
  mongodb:
    container_name: mongo
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - default-network

  back:
    build:
      context: .
      dockerfile: ./compose/back/Dockerfile-dev
    command: /start-dev.sh
    environment:
      - PORT={PORT}
      - NODE_ENV=development
      - DB_HOST=mongo
      - DB=test
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    expose:
      - "8000"
    networks:
      - default-network
    volumes:
      - ./back/:/home/service/back/
      - back_node_modules:/home/service/back/node_modules/

  front:
    build:
      context: .
      dockerfile: ./compose/front/Dockerfile-dev
    command: /start-dev.sh
    environment:
      - PORT={PORT}
      - NODE_ENV=development
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - default-network
    volumes:
      - ./front/:/home/service/front/
      - front_node_modules:/home/service/front/node_modules/

volumes:
  mongo:
  back_node_modules:
  front_node_modules:

networks:
  default-network:
    driver: bridge
